#!/bin/sh

servicedir=/var/www/html/tools/IP

showusage()
{
	echo "Invalid input!Usage:"
	echo './serviceip [ stop | start | restart ] '
	exit 1
}

start()
{
	count=$(ps aux | grep -c autochangeip.sh)
	if (( $count == 1 ))
	then
		nohup $servicedir/autochangeip.sh &
		sleep 1
		echo "autochangeip.sh start."
	else
		echo "Start failed: Another service ip is already running."
		exit 2
	fi
}


stop()
{
	count=$(ps aux | grep -c autochangeip.sh)
	#	echo $count
	if (( $count > 1 ))
	then
		if killall autochangeip.sh
		then
			echo "autochangeip.sh stop."
		else
			echo "Failed to stop autochangeip.sh!"
		fi
	else
		echo "Do not need to stop: No autochangeip.sh is running."
	fi
}


##############################################################################
#程序入口
##############################################################################

if (( $# == 1 ))
then
	if [ $1 == "start" ]
	then
		start
	elif [ $1 == "stop" ]
	then
		stop
	elif [ $1 == "restart" ]
	then
		stop
		start
	else
		showusage
	fi
else
	showusage
fi


